### PR TITLE
[FIX]: gameover effect

### LINKED ISSUE #3: [BUG] : Game overEffect
bounce for red color

### PR DESCRIPTION
**Pull request by Sharibraza**
fixed #3

//screenshot

### CODE REVIEW

File: app.js [hunk 1]
```diff
@@ -60,7 +60,7 @@ function checkAns(idx) {
 
         reset();
 
-        document.querySelector("main").style.backgroundColor = "red";
+        document.querySelector("main").style.backgroundColor = "green";
```
Comment (Sharibraza) [inline app.js:63]: it could be more better
